### ISSUE TITLE
Fix text-classifier to make it thread-safe

### ISSUE THREAD

**Issue by maudetes** [QwantResearch/text-classifier#33]
When querying text-classifier concurrently, text-classifier sometimes end up with segmentation fault.

Make text-classifier thread-safe.

**Comment by maudetes** [comment]
It appears that the issue comes from the qtokenizer library.
It has been fixed in this PR: https://github.com/QwantResearch/qnlp-toolkit/pull/2.

**Comment by cservan** [comment]
Done!
